### ISSUE TITLE
Missing library dependency declaration in a dune file

### ISSUE THREAD

**Issue by zajer** [rvantonder/hack-parallel-example#2]
In the file `src\dune` the `Core` library should be put in both `libraries` stanzas.

Everything compiles fine when the dune file looks like the following:
```
(executable
 (name main)
 (modules main)
 (libraries hack_parallel core))

(executable
 (name main_with_shared_memory)
 (modules main_with_shared_memory)
 (libraries hack_parallel core))

the rest is the same
```

**Comment by rvantonder** [comment]
You're right! Fixed in https://github.com/rvantonder/hack-parallel-example/commit/1f05325fca35433962685570da4553dd0f82b09b. I wonder why this didn't happen before (maybe a dune version thing, I'm pretty sure it worked before. No matter :-))
